services:
  proco-ebay-notifier:
    build: .
    container_name: proco-ebay-notifier
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "api.api_server:app", "--host", "0.0.0.0", "--port", "8000"]
